theme: jekyll-theme-time-machine
    -
      scope:
        path: ""
        type: "pages"
       values:
        layout: "default"
    -
      scope:
        path: "posts"
        type: "posts"
       values:
        layout: "posts"
        author: "ALE"
        

