defaults:
    -
      scope:
        path: ""
        type: "pages"
        theme: jekyll-theme-timemachine
       values:
        layout: "default"
    -
      scope:
        path: "posts"
        type: "posts"
       values:
        layout: "posts"
        author: "ALE"

theme: jekyll-theme-time-machine